stages:
  fetch:
    cmd: python src/agents/fetch.py
    deps:
      - src/agents/fetch.py
    outs:
      - data/raw/lending_club.csv

  prep:
    cmd: python src/agents/prep.py
    deps:
      - src/agents/prep.py
      - data/raw/lending_club.csv
    outs:
      - data/processed/M.parquet

  split:
    cmd: python src/agents/split.py
    deps:
      - src/agents/split.py
      - data/processed/M.parquet
    outs:
      - data/processed/train.parquet
      - data/processed/test.parquet

  train_sup:
    cmd: python src/agents/train_sup.py
    deps:
      - src/agents/train_sup.py
      - data/processed/train.parquet
      - data/processed/test.parquet
    outs:
      - models/supervised

  train_unsup:
    cmd: python src/agents/train_unsup.py
    deps:
      - src/agents/train_unsup.py
      - data/processed/train.parquet
    outs:
      - models/unsupervised

  evaluate:
    cmd: python src/agents/evaluate.py
    deps:
      - src/agents/evaluate.py
      - models/supervised
      - data/processed/test.parquet
    outs:
      - metrics/evaluation.json

  register:
    cmd: python src/agents/register.py
    deps:
      - src/agents/register.py
      - metrics/evaluation.json
    outs:
      - models/registry
