services:
  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
  credit-risk-app:
    build:
      context: ..                      # sigue usando la raíz
      dockerfile: docker/Dockerfile    # aquí le dices dónde está
    env_file:
      - ../.env
    depends_on:
      - spark-master
      - mlflow
    ports:
      - "8000:8000"
