# docker/docker-compose.yml
services:
  # 1️⃣  MLflow (backend + UI)
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    command:
      - mlflow
      - server
      - --backend-store-uri=sqlite:///data/mlflow.db
      - --default-artifact-root=/mlruns
      - --host=0.0.0.0
      - --port=5000
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_ARTIFACT_URI=/mlruns
    volumes:
      # ← el compose está en docker/, así que “../” apunta a la raíz del repo
      - ../mlruns:/mlruns
      - ../mlflow-data:/data

  # 2️⃣  Spark master
  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"

  # 3️⃣  API ­credit-risk + agentes
  credit-risk-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    environment:
      - _JAVA_OPTIONS=-Xms8g -Xmx12g
      - SPARK_DRIVER_MEMORY=10g
      - SPARK_EXECUTOR_MEMORY=8g
      - SPARK_DRIVER_MAXRESULTSIZE=3g
      - PYTHONPATH=/app
      - FAST_MODE=${FAST_MODE}
      - SAMPLE_FRACTION=${SAMPLE_FRACTION}
      - METRICS_DIR=/app/${METRICS_DIR}
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - spark-master
      - mlflow
    ports:
      - "8000:8000"
    volumes:
      - ../metrics:/app/${METRICS_DIR}
      - ../data:/app/data
